"""
PDF Report Generator using reportlab.
"""
import sys
from pathlib import Path
from datetime import datetime

sys.path.insert(0, str(Path(__file__).parent.parent.parent))
from config import REPORTS_DIR
from utils import get_logger

logger = get_logger(__name__)


class PDFReportGenerator:
    """
    Generates PDF reports from text content using reportlab.
    """
    
    def __init__(self, output_dir: str = None):
        self.output_dir = Path(output_dir) if output_dir else REPORTS_DIR
        self.output_dir.mkdir(exist_ok=True)
    
    def generate(self, title: str, content: str, filename: str = None) -> str:
        """
        Generate a PDF report from text content.
        
        Args:
            title: Report title
            content: Report content (markdown-like text)
            filename: Optional filename (auto-generated if not provided)
            
        Returns:
            Path to the generated PDF file
        """
        try:
            from reportlab.lib.pagesizes import A4
            from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
            from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer
            from reportlab.lib.enums import TA_CENTER, TA_JUSTIFY
            from reportlab.lib.colors import HexColor
        except ImportError:
            logger.error("reportlab not installed. Install with: pip install reportlab")
            raise ImportError("reportlab library required for PDF generation")
        
        if filename is None:
            timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
            filename = f"research_report_{timestamp}.pdf"
        
        if not filename.endswith(".pdf"):
            filename += ".pdf"
        
        pdf_path = self.output_dir / filename
        
        doc = SimpleDocTemplate(
            str(pdf_path),
            pagesize=A4,
            rightMargin=72,
            leftMargin=72,
            topMargin=72,
            bottomMargin=72
        )
        
        styles = getSampleStyleSheet()
        
        title_style = ParagraphStyle(
            'CustomTitle',
            parent=styles['Heading1'],
            fontSize=24,
            spaceAfter=30,
            alignment=TA_CENTER,
            textColor=HexColor('#1a365d')
        )
        
        heading_style = ParagraphStyle(
            'CustomHeading',
            parent=styles['Heading2'],
            fontSize=14,
            spaceBefore=20,
            spaceAfter=10,
            textColor=HexColor('#2c5282')
        )
        
        body_style = ParagraphStyle(
            'CustomBody',
            parent=styles['Normal'],
            fontSize=11,
            leading=16,
            alignment=TA_JUSTIFY,
            spaceAfter=12
        )
        
        bullet_style = ParagraphStyle(
            'CustomBullet',
            parent=styles['Normal'],
            fontSize=11,
            leading=14,
            leftIndent=20,
            spaceAfter=6
        )
        
        story = []
        
        story.append(Paragraph(title, title_style))
        story.append(Spacer(1, 12))
        
        date_str = datetime.now().strftime("%B %d, %Y")
        story.append(Paragraph(f"Generated: {date_str}", styles['Normal']))
        story.append(Spacer(1, 30))
        
        lines = content.split('\n')
        
        for line in lines:
            line = line.strip()
            if not line:
                story.append(Spacer(1, 6))
                continue
            
            line = line.replace('&', '&amp;').replace('<', '&lt;').replace('>', '&gt;')
            
            if line.startswith('# '):
                text = line[2:].replace('**', '').replace('*', '')
                story.append(Paragraph(text, title_style))
            elif line.startswith('## '):
                text = line[3:].replace('**', '').replace('*', '')
                story.append(Paragraph(text, heading_style))
            elif line.startswith('### '):
                text = line[4:].replace('**', '').replace('*', '')
                story.append(Paragraph(f"<b>{text}</b>", body_style))
            elif line.startswith('- ') or line.startswith('* '):
                text = line[2:].replace('**', '').replace('*', '')
                story.append(Paragraph(f"• {text}", bullet_style))
            elif line.startswith('**') and line.endswith('**'):
                text = line[2:-2]
                story.append(Paragraph(f"<b>{text}</b>", body_style))
            else:
                text = line.replace('**', '').replace('*', '')
                story.append(Paragraph(text, body_style))
        
        story.append(Spacer(1, 30))
        footer_text = "Generated by Requirements Analysis Agent Assistant (RAAA)"
        story.append(Paragraph(f"<i>{footer_text}</i>", styles['Normal']))
        
        doc.build(story)
        
        logger.info(f"PDF report generated: {pdf_path}")
        return str(pdf_path)
